#!/bin/bash
set -e

# Usage: ./build-wasm.sh
#
# Builds the Tuun synthesizer for WebAssembly.

echo "🔧 Building Tuun for WebAssembly..."

# Identify the source revision (e.g. 123abc or 123abc-dirty) so deployed
# copies can be traced back to a commit. Changes under web/pkg don't count
# as dirty: it is this script's own output, so it routinely differs from
# the committed copy.
git update-index -q --refresh
BUILD_ID=$(git rev-parse --short HEAD)
if ! git diff-index --quiet HEAD -- . ':(exclude)web/pkg' ':(exclude)docs'; then
    BUILD_ID="${BUILD_ID}-dirty"
fi

# Check if wasm-pack is installed
if ! command -v wasm-pack &> /dev/null; then
    echo "❌ wasm-pack is not installed"
    echo "Install it with: curl https://rustwasm.github.io/wasm-pack/installer/init.sh -sSf | sh"
    exit 1
fi

# Install wasm32 target if needed
echo "📦 Ensuring wasm32-unknown-unknown target is installed..."
rustup target add wasm32-unknown-unknown

echo
echo "🔨 Building with wasm-pack..."

wasm-pack build --target web --out-dir web/pkg -- --no-default-features --features wasm

# Stamp the generated JS glue with the source revision. tuun.js is
# regenerated by every build, so the stamp can't go stale.
{
    echo
    echo "// The git revision this build was made from (stamped by build-wasm.sh)."
    echo "export const tuunBuild = '${BUILD_ID}';"
} >> web/pkg/tuun.js

echo
echo "✅ Build complete! Output in web/pkg/ (build ${BUILD_ID})"
echo
echo "To test locally:"
echo "  (cd web && python3 -m http.server 8080)"
echo "  Then open http://localhost:8080 in your browser"
